title:          My Jekyll Website
description:    A simple website powered by Jekyll
theme:          minima  # You can change this later
show_excerpts:  true  # Optional: Shows post excerpts of full posts

# Navigation Links
header_pages:
- index.md
- about.md
- blog.md

sass:
  style:        compressed
