title: Riftline Games
description: Independent games. Uncompromising worlds.
url: ""
baseurl: "" # Use "/repository-name" for a GitHub project site; leave blank for a custom domain or username.github.io repo.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
timezone: America/New_York

# Files that should not be copied into the generated site.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
