title: Feedback Games
description: Independent games. Uncompromising worlds.
url: "https://feedbackgames.com" # the base hostname & protocol for your site
baseurl: "" # Use "/repository-name" for a GitHub project site; leave blank for a custom domain or username.github.io repo.

permalink: /blog/:title/

markdown: kramdown

timezone: America/New_York

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      nav_section: blog

# Files that should not be copied into the generated site.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

